# Generated by Django 3.1.7 on 2021-04-12 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210408_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
